#!/bin/sh

#
# Installation script
#
# 1) cp homologeneload.config.default homologeneload.config
# 2) Install 
# 3) cp hgncload.config.default hgncload.config
# 4) Install
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# Make sure config files exist
#
cd `dirname $0`

#
# HomoloGene
#

# establish the config files
CONFIG=homologeneload.config

# Make sure config file exists and source it
if [ -r ${CONFIG} ]
then
    echo "Source ${CONFIG}"
    . ${CONFIG}
else
    echo "Cannot source configuration file: ${CONFIG}"
    installFailed
fi

# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall for each configuration file
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

#
# Create the input directory.
#
if [ ! -d ${INPUTDIR} ]
then
    mkdir -p ${INPUTDIR}
fi

#
# HNGC
#

# establish the config files
CONFIG=hgncload.config

# Make sure config file exists and source it
if [ -r ${CONFIG} ]
then
    echo "Source ${CONFIG}"
    . ${CONFIG}
else
    echo "Cannot source configuration file: ${CONFIG}"
    installFailed
fi

# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall for each configuration file
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

#
# Create the input directory.
#
if [ ! -d ${INPUTDIR} ]
then
    mkdir -p ${INPUTDIR}
fi


