#!/bin/sh

#
# Installation script
#

Usage=Install

cd `dirname $0`

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# Make sure config files exist
#

#
# Common
#

COMMON_CONFIG=common.config

if [ ! -r ${COMMON_CONFIG} ]
then
    echo "Missing configuration file: ${COMMON_CONFIG}"
    installFailed
fi

#
# Source the common configuration file.
#
. ${COMMON_CONFIG}

#
# run DLAInstall for each configuration file
#
echo "HOMOLOGYLOAD: ${HOMOLOGYLOAD}"
for c in ${HOMOLOGYLOAD}/[a-z]*config 
do
if [ "${c}" != "${HOMOLOGYLOAD}/common.config" ]
then
    echo 'running DLAINSTALL:' ${c}
    . ${c}
    ${DLAINSTALL} ${DEV}
    #
    # Create the input directory if it doesn't exist.
    #
    if [ ! -d ${INPUTDIR} ]
    then
	mkdir -p ${INPUTDIR}
    fi
fi
done

exit 0
